export const GET_FILTERED_DATA_PROCESS = "GET_FILTERED_DATA_PROCESS";
export const GET_FILTERED_DATA_SUCCESS = "GET_FILTERED_DATA_SUCCESS";
export const GET_FILTERED_DATA_FAILURE = "GET_FILTERED_DATA_FAILURE";