
import { Inter } from "next/font/google";
import "./globals.css";
// import { Provider } from "react-redux";
import { store } from "../redux/store";
import Providers from "@/app/context/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Providers>
        <body>
          {children}
        </body>
      </Providers>
    </html>
  );
}
